service: time

provider:
  name: kubeless
  runtime: python2.7

plugins:
  - serverless-kubeless

functions:
  hellowithdata:
    handler: hellowithdata.handler
    events:
      - schedule: cron(*/10 * * * *)
      - http:
      - trigger: kafka.test.topic
